apiVersion: v1
kind: Service
metadata:
  name: loopii-service-2
spec:
  type: NodePort
  selector:
    app: loopii
    tier: frontend
  ports:
    - port: 80
      targetPort: 3040
      nodePort: 30050
